; This is chrome file upload code
WinWaitActive("Open")
Sleep(2000)
Send("D:\Accelration\New\jan_9_Selenium\Autoitfiles\testfile.txt")
Sleep(2000)
Send("{TAB}")
Sleep(2000)
Send("{TAB}")
Sleep(2000)
Send("{ENTER}")
